spring.application.name=api-gateway
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/pedidos-realm

order.service.base-url=http://localhost:8082
inventory.service.base-url=http://localhost:8083